### ISSUE TITLE
Not starting under OpenJDK

### ISSUE THREAD

**Issue by 190n** [alda-lang/alda#173]
So, I was installing Alda on my laptop, running Ubuntu 15.10 with OpenJDK 8:

```
$ java -version
openjdk version "1.8.0_66-internal"
OpenJDK Runtime Environment (build 1.8.0_66-internal-b17)
OpenJDK 64-Bit Server VM (build 25.66-b17, mixed mode)
```

I can see the help message, but I can't start the REPL, or play a test file.

Starting the REPL:

```
$ alda repl
Jan 16, 2016 6:53:04 PM com.jsyn.engine.SynthesisEngine start
INFO: Pure Java JSyn from www.softsynth.com, rate = 44100, RT, V16.7.3 (build 457, 2014-12-25)
java.lang.UnsatisfiedLinkError: no icedtea-sound in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1864)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at org.classpath.icedtea.pulseaudio.SecurityWrapper.loadNativeLibrary(SecurityWrapper.java:66)
	at org.classpath.icedtea.pulseaudio.EventLoop.<clinit>(EventLoop.java:97)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
	at com.jsyn.devices.javasound.JavaSoundAudioDevice$JavaSoundOutputStream.start(JavaSoundAudioDevice.java:209)
	at com.jsyn.engine.SynthesisEngine.run(SynthesisEngine.java:356)
	at java.lang.Thread.run(Thread.java:745)
Jan 16, 2016 6:53:04 PM com.jsyn.engine.SynthesisEngine run
INFO: JSyn synthesis thread in finally code.

 █████╗ ██╗     ██████╗  █████╗ 
██╔══██╗██║     ██╔══██╗██╔══██╗
███████║██║     ██║  ██║███████║
██╔══██║██║     ██║  ██║██╔══██║
██║  ██║███████╗██████╔╝██║  ██║
╚═╝  ╚═╝╚══════╝╚═════╝ ╚═╝  ╚═╝

            v1.0.0-rc3
         repl session

Type :help for a list of available commands. 

Loading MIDI synth... Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.classpath.icedtea.pulseaudio.EventLoop
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openImpl(PulseAudioMixer.java:654)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:588)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.openLocal(PulseAudioMixer.java:584)
	at org.classpath.icedtea.pulseaudio.PulseAudioMixer.open(PulseAudioMixer.java:579)
	at org.classpath.icedtea.pulseaudio.PulseAudioDataLine.open(PulseAudioDataLine.java:94)
	at org.classpath.icedtea.pulseaudio.PulseAudioSourceDataLine.open(PulseAudioSourceDataLine.java:75)
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1072)
	at com.sun.media.sound.SoftSynthesizer.open(SoftSynthesizer.java:1032)
	at alda.sound.midi$open_midi_synth_BANG_.invoke(midi.clj:60)
	at alda.sound$eval6812$fn__6814.doInvoke(sound.clj:26)
	at clojure.lang.RestFn.invoke(RestFn.java:423)
	at clojure.lang.MultiFn.invoke(MultiFn.java:233)
	at alda.sound$set_up_BANG_.doInvoke(sound.clj:36)
	at clojure.lang.RestFn.invoke(RestFn.java:410)
	at alda.repl$start_repl_BANG_.doInvoke(repl.clj:46)
	at clojure.lang.RestFn.invoke(RestFn.java:457)
	at clojure.lang.Var.invoke(Var.java:394)
	at clojure.lang.AFn.applyToHelper(AFn.java:165)
	at clojure.lang.Var.applyTo(Var.java:700)
	at alda.Util.callClojureFn(Util.java:197)
	at alda.AldaServer.startRepl(AldaServer.java:400)
	at alda.Client.main(Client.java:314)
```

Playing a test file:

```
$ cat test.alda
(tempo! 60)
c8 d e f g f e d c2
$ alda play -f test.alda
[27713] Starting Alda server...
[27713] Server down ✗
[27713] ERROR Connect to localhost:27713 [localhost/127.0.0.1] failed: Connection refused
```

It also works fine under Oracle's JVM.

**Comment by daveyarwood** [comment]
Looks like your OpenJDK installation doesn't include the `icedtea-sound` package. Maybe try installing the latest IcedTea from [here](http://icedtea.classpath.org/wiki/Main_Page)?
