### ISSUE TITLE
Java version problem on OS X

### ISSUE THREAD

**Issue by arthursw** [alda-lang/alda#41]
When I run `alda repl`, I get:

`Exception in thread "main" java.lang.UnsupportedClassVersionError: boot/App : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
	at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)`

`java -version`reports:
java version "1.6.0_65"
Java(TM) SE Runtime Environment (build 1.6.0_65-b14-466.1-11M4716)
Java HotSpot(TM) 64-Bit Server VM (build 20.65-b04-466.1, mixed mode)

And in Preferences > Java > Update it says: "Java 8, update 60."

**Comment by IndicaInkwell** [comment]
This is fixed by installing the latest JDK: http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html
